exam
osseous
needle
impression
technique
structures
following
cc
artery
scan
fraction
face
valve
mass
gallbladder
view
contrast
volume
lower
intravenous
femoral
injection
treatment
size
given
radiotherapy
interpretation
evaluated
ejection
distal
cord
bones
fetal
10
evidence
simulation
normal
obtained
days
mci
stress
residual
muscles
extremity
vein
ventricular
mitral
sedation
coagulation
adenopathy
aortic
described
scans
heart
recent
smk
waveform
repeated
stone
nuclear
perfusion
os
brain
dose
could
coronary
common
views
appear
along
duct
therapy
proper
may
23
venous
approximately
indication
physician
lv
test
left
diplopia
visualized
arterial
paraspinal
became
cm
sinuses
systolic
ventral
orbits
cardiac
target
injected
atrial
tricuspid
acquired
dilatation
patent
